#!/bin/bash

IMAGE_NAME=docker.io/prasanthkothuri/systemuser
IMAGE_TAG=latest

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker build \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  -t ${IMAGE_NAME}:${IMAGE_TAG} $DIR

